{% set name = "pybdei" %}
{% set version = "0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1f146d59caf0b468df86aead9953bc88da04beae4bc6b5b9278acac4c70a81e0

build:
  number: 0
  noarch: python
  entry_points:
    - bdei_infer = pybdei.inference:main
    - bdei_loglikelihood = pybdei.loglikelihood:main
    - bdei_u = pybdei.u_calculator:main
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation"
  run_exports:
    - {{ pin_subpackage('pybdei', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - numpy >= 1.24.0
    - ete3 >=3.1.3
    - python >=3.9
    - scipy >=1.11.1
    - six >=1.16.0
    - treesimulator >=0.1.22
  setup:
    - numpy >= 1.24.0
test:
  imports:
    - pybdei
  commands:
    - bdei_infer --help
    - bdei_loglikelihood --help
    - bdei_u --help

about:
  home: "https://github.com/evolbioinfo/bdei"
  summary: "Maximum likelihood estimation of Birth-Death Exposed-Infectious (BDEI) epidemiological model parameters from phylogenetic trees."
  description: |
    PastML provides tools for fast and accurate maximum likelihood estimation 
    of Birth-Death Exposed-Infectious (BDEI) epidemiological model parameters 
    from phylogenetic trees.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://github.com/evolbioinfo/bdei
  dev_url: https://github.com/evolbioinfo/bdei

extra:
  recipe-maintainers:
    - annazhukova