{% set name = "pybdei" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybdei-{{ version }}.tar.gz
  sha256: e42082d4c16aa829e2857cb5b5760f3f12f735d288e302843980f49992907111

build:
  script_env:
    - CC=g++
    - CXX=g++
  entry_points:
    - bdei_infer = pybdei.inference:main
    - bdei_loglikelihood = pybdei.loglikelihood:main
    - bdei_u = pybdei.u_calculator:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-binary=pybdei
  number: 0
  run_exports:
    - {{ pin_subpackage('pybdei', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('gxx') }}  # [linux]
  host:
    - python >=3.9
    - setuptools
    - numpy >=1.24.0
    - pip
    - gxx
    - nlopt
  run:
    - python >=3.9
    - ete3 >=3.1.3
    - scipy >=1.11.1
    - six >=1.16.0
    - treesimulator >=0.1.22
    - {{ pin_compatible('numpy >=1.24.0') }}

test:
  imports:
    - pybdei
  commands:
    - pip check
    - bdei_infer --help
    - bdei_loglikelihood --help
    - bdei_u --help
  requires:
    - pip

about:
  home: "https://github.com/evolbioinfo/bdei"
  summary: "Maximum likelihood estimation of Birth-Death Exposed-Infectious (BDEI) epidemiological model parameters from phylogenetic trees."
  description: |
    PyBDEI provides tools for fast and accurate maximum likelihood estimation 
    of Birth-Death Exposed-Infectious (BDEI) epidemiological model parameters 
    from phylogenetic trees.
  license: LGPL-2.1
  license_file: LICENSE
  license_family: GPL2
  dev_url: https://github.com/evolbioinfo/bdei

extra:
  recipe-maintainers:
    - annazhukova
  identifiers:
    - doi:10.1093/sysbio/syad059