{% set name = "phylodeep" %}
{% set version = "0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9acf1460b8533896a1e5c3e39a469c55071be187b429d70642392feaf086ae7a

build:
  number: 0
  noarch: python
  entry_points:
    - checkdeep = phylodeep.checkdeep:main
    - modeldeep = phylodeep.modeldeep:main
    - paramdeep = phylodeep.paramdeep:main
    - subtree_picker = phylodeep.tree_utilities:subtree_picker_main
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation"
  run_exports:
    - {{ pin_subpackage('phylodeep', max_pin="x.x") }}

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pandas >=1.0.0
    - scikit-learn >=1.1.3
    - tensorflow >=2.10.0
    - h5py >=3.0.0
    - keras >=2.11.0
    - matplotlib >=3.6.0
    - phylodeep-data-BD-small
    - phylodeep-data-BD-large >=0.0.2
    - phylodeep-data-BDEI-small
    - phylodeep-data-BDEI-large
    - phylodeep-data-BDSS-large
    - ete3 >=3.1.1
    - numpy >=1.22
    - python >=3.8
    - scipy >=1.5.0

test:
  imports:
    - phylodeep
  commands:
    - checkdeep --help
    - modeldeep --help
    - paramdeep --help
    - subtree_picker --help

about:
  home: "https://github.com/evolbioinfo/phylodeep"
  summary: "Deep-learning parameter estimation and model selection from phylogenetic trees."
  description: |
    PhyloDeep is a python library for parameter estimation and model selection from phylogenetic trees, 
    based on deep learning.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://github.com/evolbioinfo/phylodeep
  dev_url: https://github.com/evolbioinfo/phylodeep

extra:
  recipe-maintainers:
    - annazhukova
