{% set name = "phylodeep_data_bdei" %}
{% set version = "0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 45eec937fe786f567bf7aaaca1f4d6c442f429057744e261f6adb3ceaffbdfb5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation"
  run_exports:
    - {{ pin_subpackage('phylodeep_data_bdei', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pandas >=1.0.0

test:
  imports:
    - phylodeep_data_bdei
  commands:
    - bdei_ci_paths --help

about:
  home: "https://github.com/evolbioinfo/phylodeep_data_bdei"
  summary: "Package containing data for the phylodeep package."
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - annazhukova
